export const member = {
  id: 22,
  email: "Eveline1@yahoo.com",
  password: "1FuQeseEgs7Z9HR",
  enabled: true,
  role: "MEMBER",
  dni_cuit: "35158803",
  name: "Emily",
  imageUrl: "https://picsum.photos/300",
  address: "849 Elena Square",
  phoneNumber: "319.883.6132",
  lastPayment: "2023-04-17T18:51:50.660Z",
  description: null,
  Item: [],
  Voucher: [
    {
      id: 7,
      itemId: 40,
      userId: 22,
      code: "k9w07r7snyu1h2506gsm",
      enabled: true,
      expirationDate: "2023-08-09T05:14:16.187Z",
      item: {
        id: 40,
        userId: 3,
        categoryId: 3,
        description: " ",
        name: "Limpieza facial desincrustante",
        price: 15.99,
        imageUrl:
          "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
        discount: 20,
        enabled: true,
        category: {
          id: 3,
          name: "cosmetica",
          enabled: true,
        },
        user: {
          id: 3,
          email: "pizzahut@gmail.com",
          password: "pizza hut",
          enabled: true,
          role: "COMPANY",
          dni_cuit: "30383062410",
          name: "Pizza Hut",
          imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoMuRtRkpmAo44JrCOBYs1ByMl6XqfYx_tNw&usqp=CAU",
          address: "27310 O Kon Glen",
          phoneNumber: "(402) 805-4751 x62082",
          lastPayment: null,
          description:
            "Famosa cadena de pizzerías con una amplia variedad de pizzas y platos italianos.",
        },
      },
    },
    {
      id: 21,
      itemId: 46,
      userId: 22,
      code: "6jsu4s814bfa0i5i4wvu",
      enabled: true,
      expirationDate: "2023-08-09T05:14:16.212Z",
      item: {
        id: 46,
        userId: 18,
        categoryId: 4,
        description: " ",
        name: "Pantalones de Yoga Mujer",
        price: 0,
        imageUrl:
          "https://www.deportesevolution.com/wp-content/uploads/2022/01/La-importancia-de-la-ropa-deportiva-especifica.jpeg",
        discount: 30,
        enabled: true,
        category: {
          id: 4,
          name: "deporte",
          enabled: true,
        },
        user: {
          id: 18,
          email: "Kristina_Koelpin10@hotmail.com",
          password: "O2GlXpTu9b6ev9T",
          enabled: false,
          role: "ADMIN",
          dni_cuit: null,
          name: null,
          imageUrl: "https://picsum.photos/300",
          address: "19160 Ladarius Course",
          phoneNumber: "348.376.2291 x09209",
          lastPayment: null,
          description: null,
        },
      },
    },
    {
      id: 22,
      itemId: 13,
      userId: 22,
      code: "puxwxg1r4neevnz0rrlj",
      enabled: true,
      expirationDate: "2023-08-09T05:14:16.215Z",
      item: {
        id: 13,
        userId: 17,
        categoryId: 3,
        description: " ",
        name: "Masajes",
        price: 29.99,
        imageUrl:
          "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
        discount: 30,
        enabled: true,
        category: {
          id: 3,
          name: "cosmetica",
          enabled: true,
        },
        user: {
          id: 17,
          email: "Fern.Kunde8@gmail.com",
          password: "m14pXruZPfa_7zb",
          enabled: false,
          role: "ADMIN",
          dni_cuit: null,
          name: null,
          imageUrl: "https://picsum.photos/300",
          address: "568 Johnson Overpass",
          phoneNumber: "(924) 566-0524",
          lastPayment: null,
          description: null,
        },
      },
    },
    {
      id: 24,
      itemId: 29,
      userId: 22,
      code: "dmpy1gnmq519wz11z3tm",
      enabled: true,
      expirationDate: "2023-08-09T05:14:16.219Z",
      item: {
        id: 29,
        userId: 12,
        categoryId: 1,
        description: " ",
        name: "Pizza",
        price: 0,
        imageUrl:
          "https://www.vivepalmira.com/wp-content/uploads/2019/03/post_id_8015_91551_700x362.jpg",
        discount: 15,
        enabled: true,
        category: {
          id: 1,
          name: "comida",
          enabled: true,
        },
        user: {
          id: 12,
          email: "nike@gmail.com",
          password: "nike",
          enabled: true,
          role: "COMPANY",
          dni_cuit: "33482514064",
          name: "Nike",
          imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOFFUcd-e_1Dvl_4Ib58po4FVpMj7NyCb1JQ&usqp=CAU",
          address: "9505 May Cliff",
          phoneNumber: "247-788-1735 x229",
          lastPayment: null,
          description:
            "Marca líder en calzado y ropa deportiva, con una amplia gama de productos para atletas.",
        },
      },
    },
    {
      id: 29,
      itemId: 69,
      userId: 22,
      code: "slfbaclvwl9bqkl5a6kc",
      enabled: true,
      expirationDate: "2023-08-09T05:14:16.229Z",
      item: {
        id: 69,
        userId: 13,
        categoryId: 3,
        description: " ",
        name: "Labial Líquido",
        price: 12.99,
        imageUrl:
          "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
        discount: 25,
        enabled: true,
        category: {
          id: 3,
          name: "cosmetica",
          enabled: true,
        },
        user: {
          id: 13,
          email: "adidas@gmail.com",
          password: "adidas",
          enabled: true,
          role: "COMPANY",
          dni_cuit: "30614878834",
          name: "Adidas",
          imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1dtlrN5hP1x-m9AwA-NqGuUv2rwyehMoIkg&usqp=CAU",
          address: "648 Rogahn Passage",
          phoneNumber: "(988) 847-0931 x6627",
          lastPayment: null,
          description:
            "Otra marca líder en calzado y ropa deportiva, con énfasis en diseño y tecnología.",
        },
      },
    },
    {
      id: 35,
      itemId: 4,
      userId: 22,
      code: "3524bnkoat1970st74xz",
      enabled: true,
      expirationDate: "2023-08-09T05:14:16.240Z",
      item: {
        id: 4,
        userId: 7,
        categoryId: 2,
        description: " ",
        name: "Yogur de Durazno",
        price: 0,
        imageUrl:
          "https://www.ocu.org/-/media/ocu/images/home/alimentacion/alimentos/lacteos_blanco_.jpg?rev=04e2ca66-8851-4a07-b5d8-4c879f0d727f&hash=8B19CF9984C4138BDC89616BC096C835",
        discount: 35,
        enabled: true,
        category: {
          id: 2,
          name: "lacteos",
          enabled: true,
        },
        user: {
          id: 7,
          email: "danone@gmail.com",
          password: "danone",
          enabled: true,
          role: "COMPANY",
          dni_cuit: "32887216101",
          name: "Danone",
          imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwMKb9qjza3naK6nSdKdmHFSJfg8Z52VR0cg&usqp=CAU",
          address: "127 Armstrong Brook",
          phoneNumber: "1-649-811-4079",
          lastPayment: null,
          description:
            "Marca internacional de productos lácteos y alimentos saludables.",
        },
      },
    },
  ],
  Shopping: [
    {
      id: 8,
      userId: 22,
      pdfUrl: "http://mabelle.com",
      wayToPay: "CARD",
      state: "SUCCESS",
      Item_Shopping: [
        {
          id: 8,
          itemId: 41,
          shoppingId: 8,
          quantityItem: 7,
          item: {
            id: 41,
            userId: 17,
            categoryId: 3,
            description: " ",
            name: "Masajes",
            price: 54.99,
            imageUrl:
              "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
            discount: 20,
            enabled: true,
            category: {
              id: 3,
              name: "cosmetica",
              enabled: true,
            },
            user: {
              id: 17,
              email: "Fern.Kunde8@gmail.com",
              password: "m14pXruZPfa_7zb",
              enabled: false,
              role: "ADMIN",
              dni_cuit: null,
              name: "hola",
              imageUrl: "https://picsum.photos/300",
              address: "568 Johnson Overpass",
              phoneNumber: "(924) 566-0524",
              lastPayment: null,
              description: null,
            },
          },
        },
      ],
    },
    {
      id: 14,
      userId: 22,
      pdfUrl: "http://seth.info",
      wayToPay: "CARD",
      state: "PENDING",
      Item_Shopping: [
        {
          id: 14,
          itemId: 54,
          shoppingId: 14,
          quantityItem: 3,
          item: {
            id: 54,
            userId: 20,
            categoryId: 4,
            description: " ",
            name: "Mochila Deportiva",
            price: 0,
            imageUrl:
              "https://www.deportesevolution.com/wp-content/uploads/2022/01/La-importancia-de-la-ropa-deportiva-especifica.jpeg",
            discount: 15,
            enabled: true,
            category: {
              id: 4,
              name: "deporte",
              enabled: true,
            },
            user: {
              id: 20,
              email: "Queen85@hotmail.com",
              password: "GzAu_hjSFaTpLWc",
              enabled: false,
              role: "ADMIN",
              dni_cuit: null,
              name: null,
              imageUrl: "https://picsum.photos/300",
              address: "41025 Jerde Glen",
              phoneNumber: "817.201.9940",
              lastPayment: null,
              description: null,
            },
          },
        },
      ],
    },
    {
      id: 16,
      userId: 22,
      pdfUrl: "http://molly.name",
      wayToPay: "CASH",
      state: "SUCCESS",
      Item_Shopping: [
        {
          id: 16,
          itemId: 56,
          shoppingId: 16,
          quantityItem: 7,
          item: {
            id: 56,
            userId: 11,
            categoryId: 3,
            description: " ",
            name: "Depilacion con cera",
            price: 11.99,
            imageUrl:
              "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
            discount: 20,
            enabled: true,
            category: {
              id: 3,
              name: "cosmetica",
              enabled: true,
            },
            user: {
              id: 11,
              email: "lbel@gmail.com",
              password: "lbel",
              enabled: true,
              role: "COMPANY",
              dni_cuit: "31522149325",
              name: "L Bel",
              imageUrl:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy03pAPMNRqftBBsRQiALvVK33yWuNn4q4Mw&usqp=CAU",
              address: "3858 Braun Village",
              phoneNumber: "666.710.6610 x76747",
              lastPayment: null,
              description:
                "Marca de productos de belleza y cuidado personal, con líneas de maquillaje y perfumería.",
            },
          },
        },
      ],
    },
    {
      id: 19,
      userId: 22,
      pdfUrl: "https://abigayle.biz",
      wayToPay: "CASH",
      state: "PENDING",
      Item_Shopping: [
        {
          id: 19,
          itemId: 23,
          shoppingId: 19,
          quantityItem: 8,
          item: {
            id: 23,
            userId: 4,
            categoryId: 1,
            description: " ",
            name: "Pavo y Mostaza",
            price: 0,
            imageUrl:
              "https://www.vivepalmira.com/wp-content/uploads/2019/03/post_id_8015_91551_700x362.jpg",
            discount: 15,
            enabled: true,
            category: {
              id: 1,
              name: "comida",
              enabled: true,
            },
            user: {
              id: 4,
              email: "subway@gmail.com",
              password: "subway",
              enabled: true,
              role: "COMPANY",
              dni_cuit: "30127761460",
              name: "Subway",
              imageUrl:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSleUahmc9LVW6C4ShvKOiqixTpk2IuXijyAw&usqp=CAU",
              address: "651 Sporer Forge",
              phoneNumber: "933.214.3426",
              lastPayment: null,
              description:
                "Franquicia de sándwiches y bocadillos, conocida por sus opciones de comida fresca y personalizable",
            },
          },
        },
      ],
    },
    {
      id: 21,
      userId: 22,
      pdfUrl: "http://rudy.name",
      wayToPay: "CASH",
      state: "PENDING",
      Item_Shopping: [
        {
          id: 21,
          itemId: 49,
          shoppingId: 21,
          quantityItem: 1,
          item: {
            id: 49,
            userId: 20,
            categoryId: 4,
            description: " ",
            name: "Zapatillas Deportivas Hombre",
            price: 0,
            imageUrl:
              "https://www.deportesevolution.com/wp-content/uploads/2022/01/La-importancia-de-la-ropa-deportiva-especifica.jpeg",
            discount: 45,
            enabled: true,
            category: {
              id: 4,
              name: "deporte",
              enabled: true,
            },
            user: {
              id: 20,
              email: "Queen85@hotmail.com",
              password: "GzAu_hjSFaTpLWc",
              enabled: false,
              role: "ADMIN",
              dni_cuit: null,
              name: null,
              imageUrl: "https://picsum.photos/300",
              address: "41025 Jerde Glen",
              phoneNumber: "817.201.9940",
              lastPayment: null,
              description: null,
            },
          },
        },
      ],
    },
    {
      id: 44,
      userId: 22,
      pdfUrl: "http://hobart.biz",
      wayToPay: "CARD",
      state: "SUCCESS",
      Item_Shopping: [
        {
          id: 44,
          itemId: 47,
          shoppingId: 44,
          quantityItem: 6,
          item: {
            id: 47,
            userId: 19,
            categoryId: 4,
            description: " ",
            name: "Leggings de Compresión",
            price: 0,
            imageUrl:
              "https://www.deportesevolution.com/wp-content/uploads/2022/01/La-importancia-de-la-ropa-deportiva-especifica.jpeg",
            discount: 40,
            enabled: true,
            category: {
              id: 4,
              name: "deporte",
              enabled: true,
            },
            user: {
              id: 19,
              email: "Aditya.Miller@hotmail.com",
              password: "_vkUzkwD4hS230b",
              enabled: false,
              role: "ADMIN",
              dni_cuit: null,
              name: null,
              imageUrl: "https://picsum.photos/300",
              address: "280 Leuschke Haven",
              phoneNumber: "1-790-442-5805",
              lastPayment: null,
              description: null,
            },
          },
        },
      ],
    },
    {
      id: 45,
      userId: 22,
      pdfUrl: "http://jermain.biz",
      wayToPay: "CASH",
      state: "SUCCESS",
      Item_Shopping: [
        {
          id: 45,
          itemId: 50,
          shoppingId: 45,
          quantityItem: 1,
          item: {
            id: 50,
            userId: 20,
            categoryId: 4,
            description: " ",
            name: "Zapatillas de Running",
            price: 0,
            imageUrl:
              "https://www.deportesevolution.com/wp-content/uploads/2022/01/La-importancia-de-la-ropa-deportiva-especifica.jpeg",
            discount: 45,
            enabled: true,
            category: {
              id: 4,
              name: "deporte",
              enabled: true,
            },
            user: {
              id: 20,
              email: "Queen85@hotmail.com",
              password: "GzAu_hjSFaTpLWc",
              enabled: false,
              role: "ADMIN",
              dni_cuit: null,
              name: null,
              imageUrl: "https://picsum.photos/300",
              address: "41025 Jerde Glen",
              phoneNumber: "817.201.9940",
              lastPayment: null,
              description: null,
            },
          },
        },
      ],
    },
  ],
};

export const company = {
  id: 1,
  name: "McDonalds",
  email: "mcdonalds@gmail.com",
  role: "COMPANY",
  cuit: "33134366027",
  enabled: true,
  address: "41622 Ratke Glens",
  phoneNumber: "873-382-9467",
  description:
    "Cadena de restaurantes de comida rápida, conocida por sus hamburguesas y papas fritas.",
  imageUrl:
    "https://guiatodoberazategui.com.ar/wp-content/uploads/2020/03/Logo-de-McDonald%C2%B4s-1-1-1.png",
  items: [
    {
      id: 16,
      name: "Hamburguesa de Pollo",
      category: "comida",
      price: 0,
      discount: 20,
      enabled: true,
      imageUrl:
        "https://www.vivepalmira.com/wp-content/uploads/2019/03/post_id_8015_91551_700x362.jpg",
      vouchers: [],
      shoppings: [],
    },
    {
      id: 33,
      name: "Masaje relajante 45 min",
      category: "cosmetica",
      price: 5.99,
      discount: 30,
      enabled: true,
      imageUrl:
        "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
      vouchers: [
        {
          id: 32,
          code: "q7rx5eu42ju1yc9r707q",
          enabled: true,
          expirationDate: "2023-08-09T05:14:16.234Z",
          user: {
            id: 29,
            email: "Shanelle65@yahoo.com",
            name: "Arvid",
          },
        },
      ],
      shoppings: [],
    },
    {
      id: 71,
      name: "Masaje antiesters 45 min",
      category: "cosmetica",
      price: 8.99,
      discount: 45,
      enabled: true,
      imageUrl:
        "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
      vouchers: [],
      shoppings: [],
    },
  ],
};

export const admin = {
  id: 1,
  name: "McDonalds",
  email: "mcdonalds@gmail.com",
  role: "ADMIN",
  cuit: "33134366027",
  enabled: true,
  address: "41622 Ratke Glens",
  phoneNumber: "873-382-9467",
  description:
    "Cadena de restaurantes de comida rápida, conocida por sus hamburguesas y papas fritas.",
  imageUrl:
    "https://guiatodoberazategui.com.ar/wp-content/uploads/2020/03/Logo-de-McDonald%C2%B4s-1-1-1.png",
  items: [
    {
      id: 16,
      name: "Hamburguesa de Pollo",
      category: "comida",
      price: 0,
      discount: 20,
      enabled: true,
      imageUrl:
        "https://www.vivepalmira.com/wp-content/uploads/2019/03/post_id_8015_91551_700x362.jpg",
      vouchers: [],
      shoppings: [],
    },
    {
      id: 33,
      name: "Masaje relajante 45 min",
      category: "cosmetica",
      price: 5.99,
      discount: 30,
      enabled: true,
      imageUrl:
        "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
      vouchers: [
        {
          id: 32,
          code: "q7rx5eu42ju1yc9r707q",
          enabled: true,
          expirationDate: "2023-08-09T05:14:16.234Z",
          user: {
            id: 29,
            email: "Shanelle65@yahoo.com",
            name: "Arvid",
          },
        },
      ],
      shoppings: [],
    },
    {
      id: 71,
      name: "Masaje antiesters 45 min",
      category: "cosmetica",
      price: 8.99,
      discount: 45,
      enabled: true,
      imageUrl:
        "https://www.materialestetica.com/blog/wp-content/uploads/2019/03/cremas-para-masajes-y-sus-caracteristicas.jpg",
      vouchers: [],
      shoppings: [],
    },
  ],
};